### ISSUE TITLE
App ist not ablesbar top determine Position on Samsung Note8 After Update top android9

### ISSUE THREAD

**Issue by anka112** [ostrya/PresencePublisher#4] opened 2019-03-28 12:03 UTC
S8nce my note 8 hast been Updates to Android 9the presence präsenter ist not ablesbar to determine the Position. My State ist always schon als offline.

**Comment by ostrya** [comment] 2019-03-28 17:31
Android 9 has put more restrictions on when an app is able to read the name of the currently connected wifi network. While any app could read the wifi name in Android up to 8.1, from Android 9 onwards, an app needs to be granted the coarse or fine location permission. Additionally, the location service of the phone needs to be permanently enabled (at least "network-based location").

In theory, when you open the main activity, the app should show you a notification that you need to give it access to coarse location, and then another notification that you need to enable coarse location services.

Did you get these notifications? And have you enabled both the permission for the app and the location services?

**Comment by Albadon** [comment] 2019-05-21 13:00
My device was also having issues after upgrading to Android 9.
I don't know if you're experiencing the same issue, but I found the following message in the Logcat:
`'"MY_SSID"' does not match desired network'MY_SSID', skipping.`

#8 should fix this.

**Comment by ostrya** [comment] 2019-05-30 10:00
@anka112 Can you confirm the issue is fixed with version 1.4.2?

**Comment by ostrya** [comment] 2019-08-10 09:48
Closing issue due to missing feedback.

**Closed by ostrya** 2019-08-10 09:48 UTC
